### ISSUE TITLE
supprt setting a "nolimit" for num_requests

### ISSUE THREAD

**Issue by jeffbean** [yarpc/yab#105]
Using all parameters i am hitting the max requests over 20 minutes with 100000000000000 max requests.

```
-n -1
``` 
would do just fine :D

**Comment by blampe** [comment]
Alternatively could you use a very high number for `--max-duration`? Something like `20h`?

**Comment by prashantv** [comment]
`yab` will use whichever max it hits first, so you would have to set very high values for both. I think using `-1` to mean "don't limit by requests" makes a lot of sense.

We might have some go-flags issues to deal with first though:
```
yab -p localhost:9787 moe --health -d 5s --max-requests -1
Failed to parse options: expected argument for flag `-n, --max-requests', but got option `-1'
```

Maybe 0 should mean "no limit"?

**Comment by jeffbean** [comment]
Yeah 0 would work as well.
