### ISSUE TITLE
Support routing key and routing delegate

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yab#112]
We’ve recently added support for TChannel and HTTP routing keys and routing delegates. We should expose these with flags.

For TChannel, we will need to upgrade, then use the call options for RoutingDelegate and RoutingKey.

For HTTP, the corresponding headers are Rpc-Routing-Delegate and Rpc-Reouting-Key.

**Comment by prashantv** [comment]
This will depend on #114 since the routing key transport header in TChannel was added after the OpenTracing changes.

**Comment by kriskowal** [comment]
Fixed in #130

**Comment by prashantv** [comment]
Thanks for fixing this @kriskowal!
