### ISSUE TITLE
Support opentracing baggage

### ISSUE THREAD

**Issue by kriskowal** [yarpc/yab#113]
We now have standard ways to transport opentracing baggage with HTTP and TChannel. We should expose a --baggage flag that threads the appropriate headers for each transport.

We may need to also provide a way to configure the opentracing baggage prefix, both on the CLI and through yabrc.

**Comment by prashantv** [comment]
Currently when we pass headers, I think they're literal HTTP headers (and just application headers for TChannel). `--baggage` could exist, but then should there be a separate headers that get the right prefix?

We might need to have separate options for wire headers vs application headers

**Comment by kriskowal** [comment]
Fixed in #121, with -B and --jaeger to combine baggage and how to write them to the wire. The jaeger directive can exist in default.ini in production systems that use jaeger style baggage.
