### ISSUE TITLE
Update to latest tchannel with OpenTracing integration

### ISSUE THREAD

**Issue by prashantv** [yarpc/yab#114]
We should update all our dependencies to latest. Since we print out the trace ID when we make a request, we'll need to figure out how to make this work with the latest OpenTracing integration for TChannel.

Ideally we should not require a dependency on the Jaeger tracer.

cc @yurishkuro @kriskowal

**Comment by kriskowal** [comment]
Addressed in #121, by embedding Jaeger since it has the opinions about how to put baggage on the wire.
