### ISSUE TITLE
yab fails to benchmark with tchannel error ErrCodeBusy 

### ISSUE THREAD

**Issue by boyxgc** [yarpc/yab#154]
`yab --rps 1 -d 5s {$QUERY_PARAMS}`

Error message:

> Failed to warmup connections for benchmark: tchannel error ErrCodeBusy: {SERVICE_NAME} is rate-limited by the service rps of 100

`yab --rps 1 -d 5s --warmup 0 {$QUERY_PARAMS} can bypass this error.`

**Comment by prashantv** [comment]
@boyxgc This is not a yab issue, but is an error because the rate limit configured on the internal routing system is too low for your service.

yab is just reporting the error that the routing system returned.

**Comment by boyxgc** [comment]
@prashantv isn't my rps way below that number ?

**Comment by ZymoticB** [comment]
There are two things creating confusion here.

By default yab will issue 10 requests *per connection* as a warmup with no limit on speed. yab also defaults to 64 connections. This is why you were seeing this error with the defaults but not with `--warmup 0`
