### ISSUE TITLE
Making a GET request through Yab?

### ISSUE THREAD

**Issue by sarimzafar** [yarpc/yab#199]
Its more a question than an issue. Does Yab always make a POST call over HTTP? or can that be modified? The error I am getting when trying to make a call is `Error 405 HTTP method POST is not supported by this URL` ?

**Comment by prashantv** [comment]
@sarimzafar yab always makes a POST request with the Thrift serialized body as the POST body.

Since we have to send a body, it doesn't really make sense to use a GET request. Can you explain what use case you had in mind?

**Comment by abhinav** [comment]
Closing since there has been no follow up.

**Comment by prashantv** [comment]
Yab now allows making `GET` requests as well via `--http-method` as of #262.
