### ISSUE TITLE
Stop requiring `-t` after JSON is handled for thrift

### ISSUE THREAD

**Issue by peter-edge** [yarpc/yab#201]
If we can get thrift to work with JSON, similar to how it was just added for protobuf, then we won't need the thrift file anymore.

**Comment by prashantv** [comment]
I'm not sure I understand what you mean -- can you provide more context?

**Comment by prashantv** [comment]
Capturing an offline discussion, @peter-edge is referring to work done in https://github.com/yarpc/yarpc-go/pull/1051

However from a yab perspective, this is handled already using `-e json`. The on-wire protocol is JSON, which is handled very different from Thrift/Protobuf on the wire. If a user wants to send Thrift on the wire (which is what `-t` implies), then they will still need to specify a Thrift file.
