### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by narulacool** [yarpc/yab#223]
On using yab to access following thrift service, 

`/yab -t /home/abc/MyService.thrift -p 172.16.2.112:7625 --service TMyService --method TMyService::getFullDetails -r '{"ids":{},"appId":120}' -vv`

I am getting the below error:

`2017-10-10T18:04:59.865+0530	DEBUG	Logger initialized.	{"level": "debug"}
18:05:00.869884 [E] Failed during connection handshake. tags: [{service yab-garima} {process garima@garima-HP-ProBook-440-G1:./yab[10463]} {chID 1} {service yab-garima} {process garima@garima-HP-ProBook-440-G1:./yab[10463]} {connectionDirection outbound} {localAddr 192.168.119.132:42596} {remoteAddr 172.16.2.179:9311} {error read tcp 192.168.119.132:42596->172.16.2.179:9311: i/o timeout}]
Failed while making call: begin call failed: tchannel error ErrCodeTimeout: timeout
`

I am unable to proceed further. Please help.

**Comment by prashantv** [comment]
Are you trying to make a TChannel call? If you want http, use `http://172.16.2.112`.

**Comment by abhinav** [comment]
Assuming this is resolved.
