### ISSUE TITLE
Upgrade google.golang.org/grpc dependency

### ISSUE THREAD

**Issue by blico** [yarpc/yab#270]
yab's current version of `google.golang.org/grpc` is almost a year old: https://github.com/grpc/grpc-go/commit/32fb0ac620c32ba40a4626ddf94d90d12cce3455

**Comment by AlexAPB** [comment]
Hey @blico, can you elaborate on why/how this is causing an issue? Since grpc-go isn't pinned to a version (or even referenced in the `glide.yaml`, I'm surprised that this is causing issues building from source for a monorepo (ref T3386569).

**Comment by blico** [comment]
The monorepo has a dependency on `yab`, therefore when I upgrade the version of `grpc-go` in monorepo, I am also upgrading this dependency for `yab`. After upgrading the dependency to  https://github.com/grpc/grpc-go/commit/501c41df7f472c740d0674ff27122f3f48c80ce7 you can no longer build `yab` (or anything in monorepo that depends on it) due to the following build error:

```
com_github_yarpc_yab/protobuf/source_reflection.go:38:3: r.InitialAddrs undefined (type *manual.Resolver has no field or method InitialAddrs)
```

It appears `grpc-go` introduced an API breaking change somewhere between https://github.com/grpc/grpc-go/commit/32fb0ac620c32ba40a4626ddf94d90d12cce3455 and https://github.com/grpc/grpc-go/commit/501c41df7f472c740d0674ff27122f3f48c80ce7.

**Comment by prashantv** [comment]
yab should not be used as a dependency -- we should move off treating it as such.

To enforce this in future, we'll move subpackages of yab into an internal package.

Separately, upgrading the grpc-go dependency seems like a good idea anyway as we don't want to get too out of date.
