### ISSUE TITLE
Should all HTTP headers be displayed in the output

### ISSUE THREAD

**Issue by prashantv** [yarpc/yab#46]
When making HTTP requests, `yab` currently shows all response HTTP headers in the "headers" section. Should we be stripping common HTTP headers away (unless explicitly left on by a transport option), or should headers always be hidden?

Current output:
```json
{
  "body": {
    "result": 5
  },
  "headers": {
    "Content-Length": "23",
    "Content-Type": "application/x-thrift",
    "Date": "Wed, 01 Jun 2016 15:55:10 GMT"
  }
}
```

**Comment by blampe** [comment]
Stripping some headers would be surprising, maybe either show all or none?

**Comment by breerly** [comment]
I would show all because:

* YARPC defaults to `RPC-` prefix
* Context headers defaults to `Context-`, but one-line inits might update them, eg `YOOBERCTX-`

**Comment by prashantv** [comment]
Alright, let's leave it as showing all the headers.
