### ISSUE TITLE
HTTP/Enveloping: Support TMultiplexedProtocol

### ISSUE THREAD

**Issue by abhinav** [yarpc/yab#77]
`yab` currently does not support TMultiplexedProtocol for HTTP/Thrift services. The only difference is that instead of using the `$methodName` in the envelope, it will use `$serviceName$delimiter$methodName`, where `$delimiter` is configurable and it defaults to `:`.

**Comment by prashantv** [comment]
The separator doesn't seem configurable in [Go](https://github.com/apache/thrift/blob/master/lib/go/thrift/multiplexed_protocol.go#L61), [Java](https://github.com/apache/thrift/blob/master/lib/java/src/org/apache/thrift/protocol/TMultiplexedProtocol.java#L57) or [C++](https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/protocol/TMultiplexedProtocol.h#L71), so I think keeping it fixed as `:` should be fine.

In terms of command line, I wonder if we should collapse options so we don't end up with a bunch of Thrift options. We could have a single `--thriftOptions` which takes a list of options like `noEnvelope` and `multiplexed`. Thoughts?

**Comment by abhinav** [comment]
I think separate options makes sense. They can be grouped together into a Thrift section if necessary. Something like `--thriftOptions` limits you to comma-separated list of flags only. You won't be able to add an option with arguments.
